import Foundation
import XCTest
@testable import AoC2023

final class Day11Tests: XCTestCase {
    func testInputPart1() {
        let input = """
        ...#......
        .......#..
        #.........
        ..........
        ......#...
        .#........
        .........#
        ..........
        .......#..
        #...#.....
        """

        let result = day11part1(input: parseDay11Input(from: input))

        XCTAssertEqual(result, 374)
    }

    func testInputPart2() {
        let input = """
        ...#......
        .......#..
        #.........
        ..........
        ......#...
        .#........
        .........#
        ..........
        .......#..
        #...#.....
        """

        let result = day11part2(input: parseDay11Input(from: input))

        XCTAssertEqual(result, 82000210)
    }
}
